
spring.application.name=lab
server.compression.enabled=false
server.compression.mime-types=application/json
spring.threads.virtual.enabled=true

spring.web.resources.add-mappings=false


spring.datasource.url=jdbc:postgresql://192.168.56.101:6432/labdb?prepareThreshold=0
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

#logging.level.org.springframework.context=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
#debug=true
# Habilita log DEBUG do Hikari
#logging.level.com.zaxxer.hikari.pool.HikariPool=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
# Grava em arquivo
# logging.file.name=logs/app.log

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.url=jdbc:postgresql://192.168.56.101:6432/labdb?prepareThreshold=0
spring.flyway.user=user
spring.flyway.password=password
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10

management.endpoints.web.exposure.include=*

spring.rabbitmq.host=192.168.56.101
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

logging.level.org.springframework.web.servlet.mvc.support=ERROR


# Configurações de pool de conexões do RabbitMQ (se utilizar múltiplos canais)
spring.rabbitmq.cache.channel.size=50
# Aumenta o cache de canais para reuso simultâneo nas requisições paralelas
spring.rabbitmq.cache.channel.size=100
# Mantém múltiplos canais liberados por conexão (ajuda em picos de requisição)
spring.rabbitmq.cache.connection.mode=CHANNEL


## Aumenta o número máximo de threads no pool do servidor web
#server.tomcat.threads.max=400
## Número mínimo de threads mantidas ativas
#server.tomcat.threads.min-spare=50
## Tamanho máximo da fila de conexões pendentes
#server.tomcat.accept-count=1000
## Número máximo de conexões que o servidor pode aceitar simultaneamente
#server.tomcat.max-connections=10000



server.netty.connection-timeout=5000